dist: trusty
sudo: false
language: node_js
node_js:
- '10'
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  directories:
  - "./node_modules"
before_install:
- export TZ=Africa/Nairobi
install:
- npm install
before_script:
- npm install -g firebase-tools
- npm install -g @angular/cli
script:
- ng lint
- ng test --watch=false  --code-coverage=true --browsers=ChromeHeadless
- ng build --prod --aot
deploy:
  provider: firebase
  skip-cleanup: true
  token: $SECURE_TOKEN
env:
  global:
  - secure: SHKPk6kBk3gNiKBrMBpGiwQr6DdSoXo+yoAw6qv2wJsmOoqry8hMzqCrFTSVZ9Xj8iMe/bznPk/dTjQ2q3C4JInFKBbVpd76NkqvQPlvROJKkAwoVxa54RvXYsmuHGLP65La7C7pd1K9mGxxDxXKF7kD7EPi0lhaM/FjRBqhoHRRLQ/MwydndzmWWTUwqsXAVgkRO6DnV5iQZ+D23q/T3GUo6qF6Wss3pvEUjh4z5lJ2iSgZ9JdWS3bm0mVkMK+jLOjaib0rs3EUBnSrMCnrFFYM6NP1P85LOuMQydwmp2SzvmtnJWWYkekeOGvZNQpXu9iRn2jqPTXgvO4aZA/w/6Cx2IatfhwOjMnm/9Naao99Lfw9JTRUnbZAbbccjqpl0fX8SvVfyIB9ANnfSqNz3KifajHXazOLdfbcaPhReo1eeWuaH+SPs8DNapyEQZ6fiwrh7RPi2vpbtkkcRY7+gpMdppCuin8e6t5gYt7fFRCqrQYhm0wp+8g2mj0TNfgS0gCKhjRkZ06ANzsC9dNmE18nawHB//0o26Un4NQQNmLzNvJCvmUQbKebYCpJfNPZ0k2Oj+Tv6kPC+QNJjgmd6SBqBTRfawZbh+Hn+qv78wwDQrHZv0I9kSq1bpilgnFIY8YTE9qBLMihJVMGue2ruVP8desUI2uhajpGw8RZE+s=
after_Success:
- firebase deploy --token $SECURE_TOKEN