dist: trusty
sudo: false
language: node_js
node_js:
- '9'
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  directories:
  - "./node_modules"
before_install:
- export TZ=Africa/Nairobi
- npm install -g @angular/cli
- npm install -g firebase-tools
script:
- ng lint
- ng test --watch=false  --code-coverage=true --browsers=ChromeHeadless
- ng build --prod
deploy:
  provider: firebase
  skip-cleanup: true
  token: $SECURE_TOKEN
env:
  global:
    - secure: Mnh8q08Ar0sOcaD882ooAGWYLqaFidc9ZxQE4ywTQBCJuZ9e9IMVxMrW26yKjePkSn/dPNcUI7H6GbnqGeppkpgilYicDkYW9+OCjKAb+SDOzHpze5fhwmMHcMW6m/cB9Yh0Lj5NRG91wF/xZJ8ncL4kPIQSnA60Bz7l8c5VsF8QVKXGpWxK48j7PsaneFm3RuEvvmBg96nhg6XmoS2AANmNEfc/MfWgfHDzsFZTDqoCrdUdecO/aoVX4xGon9jwXXmVHNfr9mtu2skUSl1znoWpb7J8BQIxpYSVVwYY4Dx3Df8vfLLDUVOSneBo3LuneGmRfZzgnj36bV83gvkjR4QKTAS4DQ9KUhUhqfbr3KFdh/xVHEn4aQpGEgt+L+hXLkAaXRzF/eirR6LRMonj3Pf66aklFAVnGlpAeyX5nAcI5T8WyU2HnUy+mjoofTKxB5hiuJXidXMI93oNL5lSxVlwySkODaOpVF2TtX+XgQwY1VRK3KkapNX3wbbraiKNhl7SPMIt+LTLgw0JVPxzPzK9Y8I2c5rJvSdSr5CbQXmBu3ksg6rj97HccSzKMOKpDfxNpk1e8i2IWRUtI4heByVA5wVA3N+FOjAdibXy7echlCILQEGIeg0NOFmC4RYbLCr04ZiOlOxPkYlt04cnYj+DP0kD0/b9Q8Q8i/FcHVc=
